getScriptArguments: prevent NPE
java.lang.NullPointerException: Cannot invoke "net.runelite.api.widgets.Widget.getId()" because "scriptSource" is null